= Block4Log - Data Visibility
Sebastian Schmittner <sebastian.schmittner@eecc.de>
:toc:
:icons: font
:xrefstyle: short
:imagesdir: pix/
:tip-caption: 💡
:note-caption: ℹ️
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠️


== Data in Block4Log

Block4Log is concerned with essentially 3 types of data. Confidential documents,
such as Load Carrier (LC) exchange documents, "tokens" which document ownership,
e.g. of debt certificates, and (Block4Lock) public announcements, such a
request/offer for an amount of pallets at a specific location.


=== Load carrier exchange events

Tracking of Load Carrier (LC) exchange events is a primary concern of Block4Log. The exchange (arriving and departure) of a certain number of load carriers of a certain type/quality at a specific location and time is documented using GS1 standard data formats, in particular EPCIS events with a structure following the standard GS1 Pallet Voucher <<gs1_pallet_voucher>>.

- Signed by *both* exchanging parties

==== Data format:

-  EPCIS

- Specification: https://github.com/gs1-germany-innolab/block4log-concept-development/blob/master/epcisMessageSpecification.md
- Message examples:  https://github.com/gs1-germany-innolab/block4log-concept-development/tree/master/epcisMessageExamples
** `Option1_XML_URN.xml` is currently EPCIS 1.2 standard compliant
** JSON(-LD) is still WIP in EPCIS/CBV 2.0, likely to be released in 2020
** In EPCIS 2.0 using the digital link form of a GS1 ID might be allowed/favorable
* Example: instead of "urn:epc:idpat:grai:4000001.11111.*", 
the equivalent GS1 DL URI would look as follows: "https://id.gs1.org/8003/04000001111114".
* The latter has the OPTION to enter resolvable links into GS1's Resolver Service.
* For instance, these links could point to master data of a given party, location, or asset.

==== Visibility

* All voucher data, including meta data, might be business relevant (revealing
trade relations/volumes)
** Full read access control by signing parties required


=== Debt Tokens

Block4Log digitizes a certificate of debt which certifies that the debitor who
emitted the token owes a given number of LCs of a given type/quality to the
token owner. Debt tokens are created if there is a discrepancy between the
number of arriving and departing LCs.

- The feature of creating tradable debt tokens is to be opt-in optional.
- Any party can issue (create) debt tokens.
- The issuer is automatically the debitor.
- Whenever the issuer (debitor) is the owner, he can destroy (redeem) the token
- Tokens have a valid through date beyond which they automatically become invalid

- Standard token mechanics apply, i.e.
* Any exchange of tokens must be double-signed
* A owner must be able to produce a complete chain of direct token transfers from the issuer (debitor) to himself
 
 - Token transactions in Block4Log are tied to actual business processes, i.e. a physical or virtual exchange of assets between two parties
- Data format: TBD, Block Chain Technology dependent
* Might be ERC20 (backed) or Block4Log internal

- Attributes: 
** GDTI (Global Document Type Identifier, with serial number), using the debtor's GS1 Company Prefix
*** TBD: Individual document ID Vs fungible tokens
** deptor (PGLN)
** TBD: creationDate (Date)
*** Issuing transaction carries a timestamp anyway
** validThrough (Date)
** load carrier (GRAI) 
** qualityLevel (A, B, or C)
** TBD: quantity (positive integer)
*** Or one token per LC debt?
** TBD: eventHashes (list of underlying logistics unit exchange events) 
** Tradable (bool)
*** TBD: Do not issue non-tradable tokens in the first place



=== Public Announcements

To facilitate 

- All such announcements are opt-in optional

- Offer / Need Pallets
*** Location
*** Amount
*** Type/ quality (GS1 IDs)
*** Until
*** Contact/Service Endpoint to accept offer/start price negotiation
*** Pricing information

- Total Pallet Balance
** "Alice owes Bob a number of X Pallets"
*** Amount
*** Type/ quality (GS1 IDs)
** Publishing this kind of information does reveal that 
*** there is a trade relation
*** rough idea of trade volume (if people know some math ;) )
** Enables "Ring Exchange"
*** If A owes B, B owes C and C owes A, some amount of dept can just be cancelled without sending any payments.


=== Master data
- Data format: GS1 Smart Search, expressed as JSON-LD  
- Illustrative examples: link:masterDataExamples[Master Data Examples]

==== Parties
- GS1 Key: PGLN (Global Location Number for Parties)
- Master data attributes:
*** Party name
*** Headquarters address
** Street address one
** City 
** Postal code 
** Country code (ISO 3166-1 Alpha-2 code)

==== Locations
- GS1 Key: SGLN (Global Location Number for Physical Locations, without extension)
- Master data attributes:
*** Location name
*** Address of physical location
** Street address one
** City 
** Postal code 
** Country code (ISO 3166-1 Alpha-2 code)

==== Load Carriers
- GS1 Key: GRAI (Global Returnable Asset Identifier, without serial number part)
- Master data attributes:
*** Load carrier name
*** ??? Name of owning party (open pools)/manufacturer (open pools)
*** ??? Specification/Standard (ideally: Web Reference)
*** ??? Image
*** ??? Dimensions (length/width/depth)
*** ??? tbd

==== Voucher documents
- GS1 Key: GDTI (Global Document Type Identifier, without serial number part)
- Master data attributes:
*** Document name (String, e.g. 'Load carrier voucher')
*** Validity period (e.g. 12 months) 
*** Name of issuer
*** ??? tbd
















== Data Visibility Constraints


* Debt Notes
** Visibility constraints to be discussed
** Initial Holder/Holder history might be sensitive?

* Company IDS
** Public anyway
** Master data might be discussed

* Public Announcements
** Well... public ;)


== Conclusions for Block4Log

=== Notarization

By using Zero-Knowledge Notarization, the resulting root hash can be published
anywhere, in particular on a public block chain such as BitCoin or Ethereum, without revealing any data.
This way, the advantage of a public chain, i.e.

- Extremely low risk of loosing data / integrity
- Public availability independently from Block4Log
- No need to run the Block Chain Infrastructure

can be leveraged.


=== Confidential Data Exchange

In order to actually exchange data confidentially upon authorized request, we
still need a Block4Log internal "peer to peer layer". This function can be
provided by existing technology such as Corda, Hyperledger, etc. but also by
direct connections between the existing systems such as EPCIS repositories, ERP,
etc. which however need to be discovered/routed/connected through the Block4Log
Platform.


=== (Consortium) Public Information

To publish data within the Consortium in a public blackboard like fashion, we
may use existing block chain technology (Hyperledger, etc.) or also simpler
methods such as EPCIS repositories + discovery, MQTT or other Message brokers,
etc. 






[bibliography]
=== Quellenangaben

- [[[gs1_pallet_voucher,1]]] https://www.gs1-germany.de/fileadmin/gs1/basis_informationen/standardisierter_gs1_palettenschein.pdf

WARNING: EN Version?