= Block4Log - Data Visibility
Sebastian Schmittner <sebastian.schmittner@eecc.de>
:toc:
:icons: font
:xrefstyle: short
:imagesdir: pix/
:tip-caption: ðŸ’¡
:note-caption: â„¹ï¸
:important-caption: â—
:caution-caption: ðŸ”¥
:warning-caption: âš ï¸


== Data in Block4Log

The following types of data are going to be handled within Block4Log:

=== Load carrier exchange events
- Data format: EPCIS
- Double-signed by both exchange parties
- Specification: link:epcisMessageSpecification.md[EPCIS Message Specification]
- Message examples: link:epcisMessageExamples[EPCIS Message Examples]
** Note: only Option1_XML_URN.xml is currently GS1 standard compliant
** JSON/JSON-LD is still WIP in EPCIS/CBV 2.0
** Also, the EPCIS/CBV 2.0 working group considers to allow GS1 Digital Link URIs in addition to EPC URNs.
* Example: instead of "urn:epc:idpat:grai:4000001.11111.\*", 
the equivalent GS1 DL URI would look as follows: "https://id.gs1.org/8003/04000001111114".
* The latter had the OPTION to enter resolvable links into GS1's Resolver Service.
* For instance, these links could point to master data of a given party, location, or asset.

=== Vouchers
- Created if there is a discrepancy between arriving and departing load carriers that cannot be resolved through existing vouchers
- Can be appended (e.g. to reduce the number of owed quantities or redeem a given voucher)  
- Creation and any update must be double-signed (by passing through multi-signatures which are also used for the underlying exchange events) and tied to actual business processes (e.g. a physical or virtual exchange of assets between two parties)
- Data format: B4L-specific  
- Attributes: 
** GDTI (Global Document Type Identifier, with serial number), using the deptor's GS1 Company Prefix
** deptor (PGLN)
** creditor (PGLN)
** creationDate (Date)
** validThrough (Date)
** load carrier (GRAI) 
** qualityLevel (A, B, or C)
** quantity (list of [positive integers | 0])
** eventHashes (list of underlying logistics unit exchange events) 
** ??? status (redeemed | expired) ==> TBD: could be enabled through a smart contract that automatically sets the status to 'expired' if validThrough date is exceeded. 
** ??? tradability (true or false) ==> TBD: IMO, captured through exchange events, but not troggering a voucher as they are not tradable in the first place 

=== Public Announcements

- All such announcements are opt-in optional

- Offer / Need Pallets
*** Location
*** Amount
*** Type/ quality (GS1 IDs)
*** Until
*** Contact/Service Endpoint to accept offer/start price negotiation
*** Pricing information

- Total Pallet Balance
** "Alice owes Bob a number of X Pallets"
*** Amount
*** Type/ quality (GS1 IDs)
** Publishing this kind of information does reveal that 
*** there is a trade relation
*** rough idea of trade volume (if people know some math ;) )
** Enables "Ring Exchange"
*** If A owes B, B owes C and C owes A, some amount of dept can just be cancelled without sending any payments.


=== Master data
- Data format: GS1 Smart Search, expressed as JSON-LD  
- Illustrative examples: link:masterDataExamples[Master Data Examples]

==== Parties
- GS1 Key: PGLN (Global Location Number for Parties)
- Master data attributes:
*** Party name
*** Headquarters address
** Street address one
** City 
** Postal code 
** Country code (ISO 3166-1 Alpha-2 code)

==== Locations
- GS1 Key: SGLN (Global Location Number for Physical Locations, without extension)
- Master data attributes:
*** Location name
*** Address of physical location
** Street address one
** City 
** Postal code 
** Country code (ISO 3166-1 Alpha-2 code)

==== Load Carriers
- GS1 Key: GRAI (Global Returnable Asset Identifier, without serial number part)
- Master data attributes:
*** Load carrier name
*** ??? Name of owning party (open pools)/manufacturer (open pools)
*** ??? Specification/Standard (ideally: Web Reference)
*** ??? Image
*** ??? Dimensions (length/width/depth)
*** ??? tbd

==== Voucher documents
- GS1 Key: GDTI (Global Document Type Identifier, without serial number part)
- Master data attributes:
*** Document name (String, e.g. 'Load carrier voucher')
*** Validity period (e.g. 12 months) 
*** Name of issuer
*** ??? tbd


== Data Visibility Constraints

* All voucher data might be business relevant (revealing trade relations/volumes) 
** Full read access control by signing parties required

* Debt Notes
** Visibility constraints to be discussed
** Initial Holder/Holder history might be sensitive?

* Company IDS
** Public anyway
** Master data might be discussed

* Public Announcements
** Well... public ;)


== Conclusions for Block4Log

=== Notarization

By using Zero-Knowledge Notarization, the resulting root hash can be published
anywhere, in particular on a public block chain such as BitCoin or Ethereum, without revealing any data.
This way, the advantage of a public chain, i.e.

- Extremely low risk of loosing data / integrity
- Public availability independently from Block4Log
- No need to run the Block Chain Infrastructure

can be leveraged.


=== Confidential Data Exchange

In order to actually exchange data confidentially upon authorized request, we
still need a Block4Log internal "peer to peer layer". This function can be
provided by existing technology such as Corda, Hyperledger, etc. but also by
direct connections between the existing systems such as EPCIS repositories, ERP,
etc. which however need to be discovered/routed/connected through the Block4Log
Platform.


=== (Consortium) Public Information

To publish data within the Consortium in a public blackboard like fashion, we
may use existing block chain technology (Hyperledger, etc.) or also simpler
methods such as EPCIS repositories + discovery, MQTT or other Message brokers,
etc. 
