name: PDF Compilation

on:
  push:
    branches: [ master ]

jobs:
  md_compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        doc: ["epcisMessageSpecification", "attributeCompletenessCheck", "architecture-DLT-recommendations"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: PDF Compilation
      run: |
        npm install -g markdown-pdf
        markdown-pdf -f A4 ${{ matrix.doc }}.md

    - name: Save PDF
      uses: actions/upload-artifact@v1
      with:
        name: Block4Log-Concepts
        path: ${{ matrix.doc }}.pdf

  adoc_compile:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        doc: ["block4log-data-visibility", "zero-knowledge-notarization"]

    steps:
    - uses: actions/checkout@v2

    - name: asciidocter pdf
      uses: docker://asciidoctor/docker-asciidoctor:latest
      with:
        entrypoint: asciidoctor-pdf
        args: -a icons=font -a source-highlighter=coderay ${{ matrix.doc }}.adoc

    - name: Save PDF
      uses: actions/upload-artifact@v1
      with:
        name: Block4Log-Concepts
        path: ${{ matrix.doc }}.pdf


